/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "cls1": string|undefined
  "cls2": string|undefined
  "disabled": string|undefined
  "variant-primary": string|undefined
}
