/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "app": string|undefined
  "container-lg": string|undefined
  "container-md": string|undefined
  "container-sm": string|undefined
  "container-xl": string|undefined
  "p-1": string|undefined
  "p-10": string|undefined
  "p-2": string|undefined
  "p-3": string|undefined
  "p-4": string|undefined
  "p-5": string|undefined
  "p-6": string|undefined
  "p-7": string|undefined
  "p-8": string|undefined
  "p-9": string|undefined
}
